### ISSUE TITLE
Issues with parsing step - even with example_input

### ISSUE THREAD

**Issue by juanitagutierrez** [LohseLab/gIMble#104]
Hi!
I started using gIMble, but encountered an issue when running the parsing step. At first I thought it could be a problem with my data set (as I called variants with `bcftools` instead of `freebayes`), but it doesn't work when I try to run it using the files resulting from the preprocessing of the example_input data set either. The command that I am using looks like this:

```shell
source activate gimble
conda activate gimble

gimble/gimble parse --vcf_f mel_cyd_gimble.vcf.gz --bed_f mel_cyd_gimble.bed  --genome_f mel_cyd_gimble.genomefile --sample_f mel_cyd_gimble.samples.mod.csv --zarr mel_cyd_gimble_parse --force
``` 
Below, the error message that I am getting:

```shell
[+] Running 'gimble parse' ...
[-] Gimble datastore 'mel_cyd_gimble_parse.z' already exists.
[+] Deleting existing Gimble datastore 'mel_cyd_gimble_parse.z'
[+] Creating Gimble datastore in 'mel_cyd_gimble_parse.z'
[#] Processing GENOME_FILE '/dss/dssfs02/lwp-dss-0001/uj502/uj502-dss-0000/ra64hac/analyses_herato_hhimera/05_barrier_loci_gimble/mel_cyd_gimble.genomefile'.
[#] Processing SAMPLE_FILE '/dss/dssfs02/lwp-dss-0001/uj502/uj502-dss-0000/ra64hac/analyses_herato_hhimera/05_barrier_loci_gimble/mel_cyd_gimble.samples.mod.csv'.
[#] Processing BED_FILE '/dss/dssfs02/lwp-dss-0001/uj502/uj502-dss-0000/ra64hac/analyses_herato_hhimera/05_barrier_loci_gimble/mel_cyd_gimble.bed'.
[%] Reading intervals: 100%|██████████████████████████████████████████| 3/3 [00:00<00:00, 50.95it/s]
[#] Processing VCF_FILE '/dss/dssfs02/lwp-dss-0001/uj502/uj502-dss-0000/ra64hac/analyses_herato_hhimera/05_barrier_loci_gimble/mel_cyd_gimble.vcf.gz'.
[%] Reading variants:   0%|                                                   | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "gimble/gimble", line 8, in <module>
    main(os.path.dirname(os.path.realpath(__file__)))
  File "/dss/dssfs02/lwp-dss-0001/uj502/uj502-dss-0000/ra64hac/analyses_herato_hhimera/05_barrier_loci_gimble/gimble/cli/interface.py", line 93, in main
    runner.main(params)
  File "/dss/dssfs02/lwp-dss-0001/uj502/uj502-dss-0000/ra64hac/analyses_herato_hhimera/05_barrier_loci_gimble/gimble/cli/parse.py", line 58, in main
    vcf_f=parameterObj.vcf_f)
  File "/dss/dssfs02/lwp-dss-0001/uj502/uj502-dss-0000/ra64hac/analyses_herato_hhimera/05_barrier_loci_gimble/gimble/lib/gimble.py", line 1177, in measure
    self._read_variants(measure_key, vcf_f)
  File "/dss/dssfs02/lwp-dss-0001/uj502/uj502-dss-0000/ra64hac/analyses_herato_hhimera/05_barrier_loci_gimble/gimble/lib/gimble.py", line 1308, in _read_variants
    intervals = self._get_interval_coordinates(seq_name=seq_name)
  File "/dss/dssfs02/lwp-dss-0001/uj502/uj502-dss-0000/ra64hac/analyses_herato_hhimera/05_barrier_loci_gimble/gimble/lib/gimble.py", line 3432, in _get_interval_coordinates
    return (np.array(self.data[start_key]), np.array(self.data[end_key]))
  File "/dss/dsshome1/01/ra64hac/.conda/envs/gimble/lib/python3.7/site-packages/zarr/core.py", line 606, in __array__
    a = self[...]
  File "/dss/dsshome1/01/ra64hac/.conda/envs/gimble/lib/python3.7/site-packages/zarr/core.py", line 826, in __getitem__
    result = self.get_basic_selection(pure_selection, fields=fields)
  File "/dss/dsshome1/01/ra64hac/.conda/envs/gimble/lib/python3.7/site-packages/zarr/core.py", line 953, in get_basic_selection
    fields=fields)
  File "/dss/dsshome1/01/ra64hac/.conda/envs/gimble/lib/python3.7/site-packages/zarr/core.py", line 995, in _get_basic_selection_nd
    return self._get_selection(indexer=indexer, out=out, fields=fields)
  File "/dss/dsshome1/01/ra64hac/.conda/envs/gimble/lib/python3.7/site-packages/zarr/core.py", line 1281, in _get_selection
    if math.prod(out_shape) > 0:
AttributeError: module 'math' has no attribute 'prod'
``` 
Any idea of what might be happening? Does this look like an installation issue? Should I modify any of the .py files in zarr? 

Thanks in advance for any hint!

**Comment by DRL** [comment]
Hi juanitagutierrez,

this looks like something is broken in your installation of the `zarr` library. Not your fault.

We are currently working on a better way to install all the "weird" dependencies that `gIMble` has. 

We hope that once this is done you will not run into this error during your analyses. 

cheers, 

dom

**Comment by juanitagutierrez** [comment]
Thanks for your prompt reply, Dominik!
Great that you think this issue can be sorted out. In the meantime, do you think it would work if one installs `zarr` directly from python?

**Comment by DRL** [comment]
Honestly, the best guess right now would be trying to install dependencies with

```
conda create -n gimble python=3.8 agemo bedtools bcftools samtools vcflib mosdepth=0.3.2 pysam numpy docopt tqdm pandas tabulate zarr scikit-allel parallel matplotlib msprime demes dask numcodecs python-newick nlopt -c conda-forge -c bioconda
```

The important thing might be the `python=3.8` bit ... but i have not tested this and this is more of a hunch... but this is where i would start.

cheers,

dom

**Comment by juanitagutierrez** [comment]
Hi again,

Installing `python=3.8` instead of `python=3.7.12` indeed did the trick and I managed to run `gimble parse` with the example_input data set. Thanks for your help! I still find issues with my own data set though, so one final question would be if parsing a VCF obtained with `bcftools` instead of `freebayes` could work. 

Best,
