### ISSUE TITLE
gimbleprep reprocess.py, line 71 NameError: name 'lib' is not defined

### ISSUE THREAD

**Issue by hrluo93** [LohseLab/gIMble#116]
Hi, 

when I am running gimbleprep (installed by conda create -p /home/miniconda3/envs/gimbleprep -c bioconda gimbleprep) (conda activate gimbleprep && gimbleprep -f fisc.newzw33.now.fasta -b mkdup/ -v fisc-all.vcf.gz -k --snpgap 2 --min_qual 10 --min_depth 8 --max_depth 3) 
It showed errors:
Traceback (most recent call last):
  File "/home/miniconda3/envs/gimbleprep/bin/gimbleprep", line 10, in <module>
    sys.exit(main())
  File "/home/miniconda3/envs/gimbleprep/lib/python3.10/site-packages/gimbleprep/interface.py", line 48, in main
    runner = importlib.import_module(RUNNER_BY_MODULE[params['module']])
  File "/home/miniconda3/envs/gimbleprep/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/miniconda3/envs/gimbleprep/lib/python3.10/site-packages/gimbleprep/preprocess.py", line 71, in <module>
    class PreprocessParameterObj(lib.runargs.RunArgs):
NameError: name 'lib' is not defined

How can I solved it？

Best wishes！
Ran

**Comment by hrluo93** [comment]
or can I use old gimble preprocess command？
