### ISSUE TITLE
Not enough blocks in Gimble datastore.

### ISSUE THREAD

**Issue by ala98412** [LohseLab/gIMble#138]
Hi there,

I want to use gimble to study the differences between fission and non-fission chromosomes in closely related species.

I followed the example commands on GitHub for all previous steps.
However, when I tried to run the "gimble info" step, I received the following error.
```
[+] Getting report. This might take a while ...
[+]      Getting storage info ...
[+]      Getting parse info...
[+]      Getting blocks info...
[X] Not enough blocks in Gimble datastore.
```

I really need some help, thank you for your kind reply.

Here is my running script:
```
dataset="Fission"

# >>> step 1 parse
gimble parse -v gimble.vcf.gz -b gimble.$dataset.bed -g gimble.genomefile -s gimble.samples.csv -z analysis.$dataset

# >>> step 2 block
gimble blocks -z analysis.$dataset.z -l 64

# >>> step 3 windows
gimble windows -z analysis.$dataset.z -w 500 -s 100

# >>> step 4 tally
gimble tally -z analysis.$dataset.z -k 2,2,2,2 -l blocks_kmax2 -t blocks
gimble tally -z analysis.$dataset.z -k 2,2,2,2 -l windows_kmax2 -t windows

# >>> step 5 optimize
gimble optimize -z analysis.$dataset.z -l IM_BA_optimize -d tally/windows_kmax2 \
    -w -m IM_BA -r A -u 2.9e-09 -A 10_000,2_500_000 -B 10_000,1_000_000 \
    -C 1_000_000,5_000_000 -M 0,1e-5 -T 0,5_000_000 -g CRS2 -e 19 -i 10_000

# >>> step 6 makegrid
gimble makegrid -z analysis.$dataset.z -m IM_AB \
    -b 64 -r A -u 2.9e-9 -k 2,2,2,2 \
    -A=200_000,3_000_000,12,lin \
    -B=100_000,2_000_000,12,lin \
    -C 100_000,2_000_000,12,lin \
    -T 4_256_034 -M 0,2.21E-06,16,lin \
    -e 19 -l IM_BA_grid

# >>> step 7 gridsearch
gimble gridsearch -z analysis.$dataset.z \
    -g makegrid/IM_BA_grid -d tally/windows_kmax2 -p 50

# >>> step 8 simulate, based on fixed parameters
gimble simulate -z analysis.$dataset.z \
    --seed 19 --replicates 100 --windows 11217 --blocks 500 \
    --block_length 64 -a 10 -b 10 \
    -k 2,2,2,2 -s IM_BA_sims_100reps -p 55 -m IM_BA \
    -A 1_407_027 -B 545_041 -C 923_309 -M 7.3778010583E-07 -u 2.9e-9 -T 4_256_034

# >>> step 9 info
gimble info -z analysis.$dataset.z
```

**Comment by GertjanBisschop** [comment]
Hi @ala98412, 
Thanks for reporting this. Does this mean you can run the analysis all the way to step 9 without running into issues?
Yet, when querying the data using info it seems to say that there are no blocks to report on.

Can you generate some information on the raw zarr datastore by navigating to the directory of the zarr store and running the following bit of python code:
```{python}
import zarr
z = zarr.open('your_dataset.z')
z.tree()
```
and paste the output of that in here?

**Comment by ala98412** [comment]
Hi @GertjanBisschop ,

Thank you for replying so fast !
I've copy-paste your python code, and I got error message.

Did I do anything wrong?

```
Traceback (most recent call last):
  File "zarr.py", line 3, in <module>
    import zarr
  File "/home/JuiHung/gIMble/zarr.py", line 4, in <module>
    z = zarr.open('analysis.Fission.z')
AttributeError: module 'zarr' has no attribute 'open'
```

Here is my code, I believe I only changed the folder name.
```
#!/usr/bin/env python3

import zarr
z = zarr.open('analysis.Fission.z')
z.tree()
```

By the way, I install zarr using the following command:
`pip3 install zarr`

Hope these would help to solving my problems.

Thank you very much !

**Comment by ala98412** [comment]
Hi @GertjanBisschop, 

Yes, I can run all steps and without any error or warning messages.
Basicly I run step-by-step to make sure there's no any wrong.

I fixed my stupid mistake.
Here is the output of zarr

```
/
 ├── blocks
 │   ├── HiC_scaffold_1
 │   │   └── 0
 │   │       ├── ends (473604,) int64
 │   │       ├── missing (473604, 1) int64
 │   │       ├── multiallelic (473604, 1) int64
 │   │       ├── starts (473604,) int64
 │   │       └── variation (473604, 4) int64
 │   ├── HiC_scaffold_10
 │   │   └── 0
 │   │       ├── ends (361602,) int64
 │   │       ├── missing (361602, 1) int64
 │   │       ├── multiallelic (361602, 1) int64
 │   │       ├── starts (361602,) int64
 │   │       └── variation (361602, 4) int64
 │   ├── HiC_scaffold_13
 │   │   └── 0
 │   │       ├── ends (307729,) int64
 │   │       ├── missing (307729, 1) int64
 │   │       ├── multiallelic (307729, 1) int64
 │   │       ├── starts (307729,) int64
 │   │       └── variation (307729, 4) int64
 │   ├── HiC_scaffold_15
 │   │   └── 0
 │   │       ├── ends (323238,) int64
 │   │       ├── missing (323238, 1) int64
 │   │       ├── multiallelic (323238, 1) int64
 │   │       ├── starts (323238,) int64
 │   │       └── variation (323238, 4) int64
 │   ├── HiC_scaffold_16
 │   │   └── 0
 │   │       ├── ends (320186,) int64
 │   │       ├── missing (320186, 1) int64
 │   │       ├── multiallelic (320186, 1) int64
 │   │       ├── starts (320186,) int64
 │   │       └── variation (320186, 4) int64
 │   ├── HiC_scaffold_18
 │   │   └── 0
 │   │       ├── ends (302357,) int64
 │   │       ├── missing (302357, 1) int64
 │   │       ├── multiallelic (302357, 1) int64
 │   │       ├── starts (302357,) int64
 │   │       └── variation (302357, 4) int64
 │   ├── HiC_scaffold_2
 │   │   └── 0
 │   │       ├── ends (479723,) int64
 │   │       ├── missing (479723, 1) int64
 │   │       ├── multiallelic (479723, 1) int64
 │   │       ├── starts (479723,) int64
 │   │       └── variation (479723, 4) int64
 │   ├── HiC_scaffold_20
 │   │   └── 0
 │   │       ├── ends (289632,) int64
 │   │       ├── missing (289632, 1) int64
 │   │       ├── multiallelic (289632, 1) int64
 │   │       ├── starts (289632,) int64
 │   │       └── variation (289632, 4) int64
 │   ├── HiC_scaffold_21
 │   │   └── 0
 │   │       ├── ends (273479,) int64
 │   │       ├── missing (273479, 1) int64
 │   │       ├── multiallelic (273479, 1) int64
 │   │       ├── starts (273479,) int64
 │   │       └── variation (273479, 4) int64
 │   ├── HiC_scaffold_22
 │   │   └── 0
 │   │       ├── ends (281752,) int64
 │   │       ├── missing (281752, 1) int64
 │   │       ├── multiallelic (281752, 1) int64
 │   │       ├── starts (281752,) int64
 │   │       └── variation (281752, 4) int64
 │   ├── HiC_scaffold_3
 │   │   └── 0
 │   │       ├── ends (441265,) int64
 │   │       ├── missing (441265, 1) int64
 │   │       ├── multiallelic (441265, 1) int64
 │   │       ├── starts (441265,) int64
 │   │       └── variation (441265, 4) int64
 │   ├── HiC_scaffold_5
 │   │   └── 0
 │   │       ├── ends (397829,) int64
 │   │       ├── missing (397829, 1) int64
 │   │       ├── multiallelic (397829, 1) int64
 │   │       ├── starts (397829,) int64
 │   │       └── variation (397829, 4) int64
 │   ├── HiC_scaffold_7
 │   │   └── 0
 │   │       ├── ends (351650,) int64
 │   │       ├── missing (351650, 1) int64
 │   │       ├── multiallelic (351650, 1) int64
 │   │       ├── starts (351650,) int64
 │   │       └── variation (351650, 4) int64
 │   ├── HiC_scaffold_8
 │   │   └── 0
 │   │       ├── ends (343350,) int64
 │   │       ├── missing (343350, 1) int64
 │   │       ├── multiallelic (343350, 1) int64
 │   │       ├── starts (343350,) int64
 │   │       └── variation (343350, 4) int64
 │   └── HiC_scaffold_9
 │       └── 0
 │           ├── ends (337545,) int64
 │           ├── missing (337545, 1) int64
 │           ├── multiallelic (337545, 1) int64
 │           ├── starts (337545,) int64
 │           └── variation (337545, 4) int64
 ├── gridsearch
 │   └── windows_kmax2
 │       └── IM_BA_grid
 │           └── 0 (52783, 27648) float64
 ├── makegrid
 │   └── IM_BA_grid (27648, 4, 4, 4, 4) float64
 ├── optimize
 │   └── windows_kmax2.windowsum
 │       └── IM_BA_optimize
 │           └── 0 (10000, 14) float64
 ├── seqs
 │   ├── HiC_scaffold_1
 │   │   ├── intervals
 │   │   │   ├── ends (1242037,) int64
 │   │   │   ├── matrix (1242037, 2) int64
 │   │   │   └── starts (1242037,) int64
 │   │   └── variants
 │   │       ├── matrix (1342175, 2, 2) int64
 │   │       └── pos (1342175,) int64
 │   ├── HiC_scaffold_10
 │   │   ├── intervals
 │   │   │   ├── ends (854856,) int64
 │   │   │   ├── matrix (854856, 2) int64
 │   │   │   └── starts (854856,) int64
 │   │   └── variants
 │   │       ├── matrix (994193, 2, 2) int64
 │   │       └── pos (994193,) int64
 │   ├── HiC_scaffold_13
 │   │   ├── intervals
 │   │   │   ├── ends (843767,) int64
 │   │   │   ├── matrix (843767, 2) int64
 │   │   │   └── starts (843767,) int64
 │   │   └── variants
 │   │       ├── matrix (877367, 2, 2) int64
 │   │       └── pos (877367,) int64
 │   ├── HiC_scaffold_15
 │   │   ├── intervals
 │   │   │   ├── ends (804604,) int64
 │   │   │   ├── matrix (804604, 2) int64
 │   │   │   └── starts (804604,) int64
 │   │   └── variants
 │   │       ├── matrix (900397, 2, 2) int64
 │   │       └── pos (900397,) int64
 │   ├── HiC_scaffold_16
 │   │   ├── intervals
 │   │   │   ├── ends (813598,) int64
 │   │   │   ├── matrix (813598, 2) int64
 │   │   │   └── starts (813598,) int64
 │   │   └── variants
 │   │       ├── matrix (889663, 2, 2) int64
 │   │       └── pos (889663,) int64
 │   ├── HiC_scaffold_18
 │   │   ├── intervals
 │   │   │   ├── ends (802920,) int64
 │   │   │   ├── matrix (802920, 2) int64
 │   │   │   └── starts (802920,) int64
 │   │   └── variants
 │   │       ├── matrix (845881, 2, 2) int64
 │   │       └── pos (845881,) int64
 │   ├── HiC_scaffold_2
 │   │   ├── intervals
 │   │   │   ├── ends (1184474,) int64
 │   │   │   ├── matrix (1184474, 2) int64
 │   │   │   └── starts (1184474,) int64
 │   │   └── variants
 │   │       ├── matrix (1364984, 2, 2) int64
 │   │       └── pos (1364984,) int64
 │   ├── HiC_scaffold_20
 │   │   ├── intervals
 │   │   │   ├── ends (773159,) int64
 │   │   │   ├── matrix (773159, 2) int64
 │   │   │   └── starts (773159,) int64
 │   │   └── variants
 │   │       ├── matrix (838936, 2, 2) int64
 │   │       └── pos (838936,) int64
 │   ├── HiC_scaffold_21
 │   │   ├── intervals
 │   │   │   ├── ends (730460,) int64
 │   │   │   ├── matrix (730460, 2) int64
 │   │   │   └── starts (730460,) int64
 │   │   └── variants
 │   │       ├── matrix (763700, 2, 2) int64
 │   │       └── pos (763700,) int64
 │   ├── HiC_scaffold_22
 │   │   ├── intervals
 │   │   │   ├── ends (713522,) int64
 │   │   │   ├── matrix (713522, 2) int64
 │   │   │   └── starts (713522,) int64
 │   │   └── variants
 │   │       ├── matrix (775947, 2, 2) int64
 │   │       └── pos (775947,) int64
 │   ├── HiC_scaffold_3
 │   │   ├── intervals
 │   │   │   ├── ends (1119903,) int64
 │   │   │   ├── matrix (1119903, 2) int64
 │   │   │   └── starts (1119903,) int64
 │   │   └── variants
 │   │       ├── matrix (1241903, 2, 2) int64
 │   │       └── pos (1241903,) int64
 │   ├── HiC_scaffold_5
 │   │   ├── intervals
 │   │   │   ├── ends (1058848,) int64
 │   │   │   ├── matrix (1058848, 2) int64
 │   │   │   └── starts (1058848,) int64
 │   │   └── variants
 │   │       ├── matrix (1128303, 2, 2) int64
 │   │       └── pos (1128303,) int64
 │   ├── HiC_scaffold_7
 │   │   ├── intervals
 │   │   │   ├── ends (951097,) int64
 │   │   │   ├── matrix (951097, 2) int64
 │   │   │   └── starts (951097,) int64
 │   │   └── variants
 │   │       ├── matrix (1000012, 2, 2) int64
 │   │       └── pos (1000012,) int64
 │   ├── HiC_scaffold_8
 │   │   ├── intervals
 │   │   │   ├── ends (913305,) int64
 │   │   │   ├── matrix (913305, 2) int64
 │   │   │   └── starts (913305,) int64
 │   │   └── variants
 │   │       ├── matrix (978163, 2, 2) int64
 │   │       └── pos (978163,) int64
 │   └── HiC_scaffold_9
 │       ├── intervals
 │       │   ├── ends (879164,) int64
 │       │   ├── matrix (879164, 2) int64
 │       │   └── starts (879164,) int64
 │       └── variants
 │           ├── matrix (953521, 2, 2) int64
 │           └── pos (953521,) int64
 ├── simulate
 │   └── IM_BA_sims_100reps
 │       ├── 0 (11217, 4, 4, 4, 4) int64
 │       ├── 1 (11217, 4, 4, 4, 4) int64
 │       ├── 10 (11217, 4, 4, 4, 4) int64
 │       ├── 11 (11217, 4, 4, 4, 4) int64
 │       ├── 12 (11217, 4, 4, 4, 4) int64
 │       ├── 13 (11217, 4, 4, 4, 4) int64
 │       ├── 14 (11217, 4, 4, 4, 4) int64
 │       ├── 15 (11217, 4, 4, 4, 4) int64
 │       ├── 16 (11217, 4, 4, 4, 4) int64
 │       ├── 17 (11217, 4, 4, 4, 4) int64
 │       ├── 18 (11217, 4, 4, 4, 4) int64
 │       ├── 19 (11217, 4, 4, 4, 4) int64
 │       ├── 2 (11217, 4, 4, 4, 4) int64
 │       ├── 20 (11217, 4, 4, 4, 4) int64
 │       ├── 21 (11217, 4, 4, 4, 4) int64
 │       ├── 22 (11217, 4, 4, 4, 4) int64
 │       ├── 23 (11217, 4, 4, 4, 4) int64
 │       ├── 24 (11217, 4, 4, 4, 4) int64
 │       ├── 25 (11217, 4, 4, 4, 4) int64
 │       ├── 26 (11217, 4, 4, 4, 4) int64
 │       ├── 27 (11217, 4, 4, 4, 4) int64
 │       ├── 28 (11217, 4, 4, 4, 4) int64
 │       ├── 29 (11217, 4, 4, 4, 4) int64
 │       ├── 3 (11217, 4, 4, 4, 4) int64
 │       ├── 30 (11217, 4, 4, 4, 4) int64
 │       ├── 31 (11217, 4, 4, 4, 4) int64
 │       ├── 32 (11217, 4, 4, 4, 4) int64
 │       ├── 33 (11217, 4, 4, 4, 4) int64
 │       ├── 34 (11217, 4, 4, 4, 4) int64
 │       ├── 35 (11217, 4, 4, 4, 4) int64
 │       ├── 36 (11217, 4, 4, 4, 4) int64
 │       ├── 37 (11217, 4, 4, 4, 4) int64
 │       ├── 38 (11217, 4, 4, 4, 4) int64
 │       ├── 39 (11217, 4, 4, 4, 4) int64
 │       ├── 4 (11217, 4, 4, 4, 4) int64
 │       ├── 40 (11217, 4, 4, 4, 4) int64
 │       ├── 41 (11217, 4, 4, 4, 4) int64
 │       ├── 42 (11217, 4, 4, 4, 4) int64
 │       ├── 43 (11217, 4, 4, 4, 4) int64
 │       ├── 44 (11217, 4, 4, 4, 4) int64
 │       ├── 45 (11217, 4, 4, 4, 4) int64
 │       ├── 46 (11217, 4, 4, 4, 4) int64
 │       ├── 47 (11217, 4, 4, 4, 4) int64
 │       ├── 48 (11217, 4, 4, 4, 4) int64
 │       ├── 49 (11217, 4, 4, 4, 4) int64
 │       ├── 5 (11217, 4, 4, 4, 4) int64
 │       ├── 50 (11217, 4, 4, 4, 4) int64
 │       ├── 51 (11217, 4, 4, 4, 4) int64
 │       ├── 52 (11217, 4, 4, 4, 4) int64
 │       ├── 53 (11217, 4, 4, 4, 4) int64
 │       ├── 54 (11217, 4, 4, 4, 4) int64
 │       ├── 55 (11217, 4, 4, 4, 4) int64
 │       ├── 56 (11217, 4, 4, 4, 4) int64
 │       ├── 57 (11217, 4, 4, 4, 4) int64
 │       ├── 58 (11217, 4, 4, 4, 4) int64
 │       ├── 59 (11217, 4, 4, 4, 4) int64
 │       ├── 6 (11217, 4, 4, 4, 4) int64
 │       ├── 60 (11217, 4, 4, 4, 4) int64
 │       ├── 61 (11217, 4, 4, 4, 4) int64
 │       ├── 62 (11217, 4, 4, 4, 4) int64
 │       ├── 63 (11217, 4, 4, 4, 4) int64
 │       ├── 64 (11217, 4, 4, 4, 4) int64
 │       ├── 65 (11217, 4, 4, 4, 4) int64
 │       ├── 66 (11217, 4, 4, 4, 4) int64
 │       ├── 67 (11217, 4, 4, 4, 4) int64
 │       ├── 68 (11217, 4, 4, 4, 4) int64
 │       ├── 69 (11217, 4, 4, 4, 4) int64
 │       ├── 7 (11217, 4, 4, 4, 4) int64
 │       ├── 70 (11217, 4, 4, 4, 4) int64
 │       ├── 71 (11217, 4, 4, 4, 4) int64
 │       ├── 72 (11217, 4, 4, 4, 4) int64
 │       ├── 73 (11217, 4, 4, 4, 4) int64
 │       ├── 74 (11217, 4, 4, 4, 4) int64
 │       ├── 75 (11217, 4, 4, 4, 4) int64
 │       ├── 76 (11217, 4, 4, 4, 4) int64
 │       ├── 77 (11217, 4, 4, 4, 4) int64
 │       ├── 78 (11217, 4, 4, 4, 4) int64
 │       ├── 79 (11217, 4, 4, 4, 4) int64
 │       ├── 8 (11217, 4, 4, 4, 4) int64
 │       ├── 80 (11217, 4, 4, 4, 4) int64
 │       ├── 81 (11217, 4, 4, 4, 4) int64
 │       ├── 82 (11217, 4, 4, 4, 4) int64
 │       ├── 83 (11217, 4, 4, 4, 4) int64
 │       ├── 84 (11217, 4, 4, 4, 4) int64
 │       ├── 85 (11217, 4, 4, 4, 4) int64
 │       ├── 86 (11217, 4, 4, 4, 4) int64
 │       ├── 87 (11217, 4, 4, 4, 4) int64
 │       ├── 88 (11217, 4, 4, 4, 4) int64
 │       ├── 89 (11217, 4, 4, 4, 4) int64
 │       ├── 9 (11217, 4, 4, 4, 4) int64
 │       ├── 90 (11217, 4, 4, 4, 4) int64
 │       ├── 91 (11217, 4, 4, 4, 4) int64
 │       ├── 92 (11217, 4, 4, 4, 4) int64
 │       ├── 93 (11217, 4, 4, 4, 4) int64
 │       ├── 94 (11217, 4, 4, 4, 4) int64
 │       ├── 95 (11217, 4, 4, 4, 4) int64
 │       ├── 96 (11217, 4, 4, 4, 4) int64
 │       ├── 97 (11217, 4, 4, 4, 4) int64
 │       ├── 98 (11217, 4, 4, 4, 4) int64
 │       └── 99 (11217, 4, 4, 4, 4) int64
 ├── tally
 │   ├── blocks_kmax2 (4, 4, 4, 4) uint32
 │   ├── blocks_raw (9, 9, 9, 9) uint32
 │   ├── windows_kmax2 (52783, 4, 4, 4, 4) uint16
 │   └── windows_raw (2429160, 6) uint16
 └── windows
     ├── HiC_scaffold_1
     │   ├── balance (4732,) float64
     │   ├── ends (4732,) int64
     │   ├── mse_sample_set_cov (4732,) float64
     │   ├── pos_mean (4732,) float64
     │   ├── pos_median (4732,) float64
     │   ├── starts (4732,) int64
     │   └── variation (4732, 500, 4) int64
     ├── HiC_scaffold_10
     │   ├── balance (3612,) float64
     │   ├── ends (3612,) int64
     │   ├── mse_sample_set_cov (3612,) float64
     │   ├── pos_mean (3612,) float64
     │   ├── pos_median (3612,) float64
     │   ├── starts (3612,) int64
     │   └── variation (3612, 500, 4) int64
     ├── HiC_scaffold_13
     │   ├── balance (3073,) float64
     │   ├── ends (3073,) int64
     │   ├── mse_sample_set_cov (3073,) float64
     │   ├── pos_mean (3073,) float64
     │   ├── pos_median (3073,) float64
     │   ├── starts (3073,) int64
     │   └── variation (3073, 500, 4) int64
     ├── HiC_scaffold_15
     │   ├── balance (3228,) float64
     │   ├── ends (3228,) int64
     │   ├── mse_sample_set_cov (3228,) float64
     │   ├── pos_mean (3228,) float64
     │   ├── pos_median (3228,) float64
     │   ├── starts (3228,) int64
     │   └── variation (3228, 500, 4) int64
     ├── HiC_scaffold_16
     │   ├── balance (3197,) float64
     │   ├── ends (3197,) int64
     │   ├── mse_sample_set_cov (3197,) float64
     │   ├── pos_mean (3197,) float64
     │   ├── pos_median (3197,) float64
     │   ├── starts (3197,) int64
     │   └── variation (3197, 500, 4) int64
     ├── HiC_scaffold_18
     │   ├── balance (3019,) float64
     │   ├── ends (3019,) int64
     │   ├── mse_sample_set_cov (3019,) float64
     │   ├── pos_mean (3019,) float64
     │   ├── pos_median (3019,) float64
     │   ├── starts (3019,) int64
     │   └── variation (3019, 500, 4) int64
     ├── HiC_scaffold_2
     │   ├── balance (4793,) float64
     │   ├── ends (4793,) int64
     │   ├── mse_sample_set_cov (4793,) float64
     │   ├── pos_mean (4793,) float64
     │   ├── pos_median (4793,) float64
     │   ├── starts (4793,) int64
     │   └── variation (4793, 500, 4) int64
     ├── HiC_scaffold_20
     │   ├── balance (2892,) float64
     │   ├── ends (2892,) int64
     │   ├── mse_sample_set_cov (2892,) float64
     │   ├── pos_mean (2892,) float64
     │   ├── pos_median (2892,) float64
     │   ├── starts (2892,) int64
     │   └── variation (2892, 500, 4) int64
     ├── HiC_scaffold_21
     │   ├── balance (2730,) float64
     │   ├── ends (2730,) int64
     │   ├── mse_sample_set_cov (2730,) float64
     │   ├── pos_mean (2730,) float64
     │   ├── pos_median (2730,) float64
     │   ├── starts (2730,) int64
     │   └── variation (2730, 500, 4) int64
     ├── HiC_scaffold_22
     │   ├── balance (2813,) float64
     │   ├── ends (2813,) int64
     │   ├── mse_sample_set_cov (2813,) float64
     │   ├── pos_mean (2813,) float64
     │   ├── pos_median (2813,) float64
     │   ├── starts (2813,) int64
     │   └── variation (2813, 500, 4) int64
     ├── HiC_scaffold_3
     │   ├── balance (4408,) float64
     │   ├── ends (4408,) int64
     │   ├── mse_sample_set_cov (4408,) float64
     │   ├── pos_mean (4408,) float64
     │   ├── pos_median (4408,) float64
     │   ├── starts (4408,) int64
     │   └── variation (4408, 500, 4) int64
     ├── HiC_scaffold_5
     │   ├── balance (3974,) float64
     │   ├── ends (3974,) int64
     │   ├── mse_sample_set_cov (3974,) float64
     │   ├── pos_mean (3974,) float64
     │   ├── pos_median (3974,) float64
     │   ├── starts (3974,) int64
     │   └── variation (3974, 500, 4) int64
     ├── HiC_scaffold_7
     │   ├── balance (3512,) float64
     │   ├── ends (3512,) int64
     │   ├── mse_sample_set_cov (3512,) float64
     │   ├── pos_mean (3512,) float64
     │   ├── pos_median (3512,) float64
     │   ├── starts (3512,) int64
     │   └── variation (3512, 500, 4) int64
     ├── HiC_scaffold_8
     │   ├── balance (3429,) float64
     │   ├── ends (3429,) int64
     │   ├── mse_sample_set_cov (3429,) float64
     │   ├── pos_mean (3429,) float64
     │   ├── pos_median (3429,) float64
     │   ├── starts (3429,) int64
     │   └── variation (3429, 500, 4) int64
     └── HiC_scaffold_9
         ├── balance (3371,) float64
         ├── ends (3371,) int64
         ├── mse_sample_set_cov (3371,) float64
         ├── pos_mean (3371,) float64
         ├── pos_median (3371,) float64
         ├── starts (3371,) int64
         └── variation (3371, 500, 4) int64
```

**Comment by ala98412** [comment]
Hi @GertjanBisschop, 

This remind me that I did faced some wierd error at the begining.

When I use **gimbleprep** for data preparation,
The output sample file (gimble.samples.csv) only contains **sample_id**.
However, **gimble parse** give me the error message:

```
[+] Running 'gimble parse' ...
[+] Creating Gimble datastore in 'analysis.z'
[#] Processing GENOME_FILE '/home/why/Tools/gIMble/example_input/gimble.genomefile'.
[#] Processing SAMPLE_FILE '/home/why/Tools/gIMble/example_input/gimble.samples.csv'.
[X] --sample_f '/home/why/Tools/gIMble/example_input/gimble.samples.csv' can't be parsed. Make sure it is a CSV file composed of two columns (sample ID and population ID).
```

Hence, I add population ID manually.
Could this potentially outcome some error?

**Comment by GertjanBisschop** [comment]
The zarr store can be thought of as a hierarchical collection of arrays where each level of the hierarchy can be assigned some metadata. You should be able to access this by looking at the attributes or `attrs` of each level.

```{python}
import zarr

root = zarr.open('zarrstore.z')
print(root.attrs.asdict())
print(root['blocks'].attrs.asdict())
print(root['blocks/HiC_scaffold_1'].attrs.asdict())
```
Could you paste this in as well?

**Comment by ala98412** [comment]
Hi @GertjanBisschop,

Here is the output !

```
{'blocks': '/home/JuiHung/anaconda3/lib/python3.11/site-packages/cli/interface.py/gimble blocks --zstore /home/JuiHung/gIMble/analysis.Fission.z --block_length 64 --block_span 128 --block_max_multiallelic 3 --block_max_missing 3 --overwrite False ', 'parse': '/home/JuiHung/anaconda3/lib/python3.11/site-packages/cli/interface.py/gimble parse --vcf_f /home/JuiHung/gIMble/gimble.vcf.gz --bed_f /home/JuiHung/gIMble/gimble.Fission.bed --genome_f /home/JuiHung/gIMble/gimble.genomefile --sample_f /home/JuiHung/gIMble/gimble.samples.csv --outprefix analysis.Fission --overwrite False ', 'windows': '/home/JuiHung/anaconda3/lib/python3.11/site-packages/cli/interface.py/gimble windows --zstore /home/JuiHung/gIMble/analysis.Fission.z --window_size 500 --window_step 100 --overwrite False '}
{'blocks_raw_tally_key': 'tally/blocks_raw', 'count_by_sample_set_idx': {'0': 5284941}, 'count_by_sequence': {'HiC_scaffold_1': 473604, 'HiC_scaffold_10': 361602, 'HiC_scaffold_13': 307729, 'HiC_scaffold_15': 323238, 'HiC_scaffold_16': 320186, 'HiC_scaffold_18': 302357, 'HiC_scaffold_2': 479723, 'HiC_scaffold_20': 289632, 'HiC_scaffold_21': 273479, 'HiC_scaffold_22': 281752, 'HiC_scaffold_3': 441265, 'HiC_scaffold_5': 397829, 'HiC_scaffold_7': 351650, 'HiC_scaffold_8': 343350, 'HiC_scaffold_9': 337545}, 'count_raw_by_sample_set_idx': {'0': 5290381}, 'count_total': 5284941, 'count_total_raw': 5290381, 'length': 64, 'max_missing': 3, 'max_multiallelic': 3, 'span': 128}
{}
```

Also I am wondering whether I need to give more samples?
I only gave 1 sample per species.

What I literally do is mapping two samples (difference species) to same reference genome. And then I seperate **gimble.bed** to two bed file (gimble.fission.bed and gimble.nonfission.bed) base on the chromosome type which I classified earlier.
Furthermore, I use whole genome, instead of just intergenic region.

Hope these information could be helpful.
Thank you very much.

**Comment by KLohse** [comment]
Hi @ala98412,

Many thanks for reporting this! The error you are getting:
`[X] Not enough blocks in Gimble datastore.`

when running gimble info is a consequence of your sample size of 1 per population/species. At the moment `gimble info` cannot handle datasets that include populations with only one sampled individual. This  bug is annoying and needs to be fixed and we are working on this. Importantly however, it does not affect downstream analyses. 

Hope this helps,
Konrad

**Comment by ala98412** [comment]
Hi @KLohse,

Thank you for the response.

I would like to have output like Figure 4B of"**Chromosome Fissions and Fusions Act as Barriers to Gene Flow between Brenthis Fritillary Butterflies**".

This will not raise any problems right?

Although the major problem is I don't know how to get the result. :'(


And also thank you @GertjanBisschop !

**Comment by GertjanBisschop** [comment]
pinging @A-J-F-Mackintosh . Is there a notebook/script deposited somewhere associated with that manuscript?

**Comment by A-J-F-Mackintosh** [comment]
Hi all,

There is no notebook associated with the analysis for that manuscript. However, I pretty much used the standard gIMble pipeline and then labelled windows by (i) whether the chromosome was rearranged and (ii) whether it was within 1 Mb of a rearrangements point.

@ala98412's pipeline looks good to me. They just need to use `gIMble query` to get the result of the gridsearch, e.g.

`gimble query -z my_analysis.z -l gridsearch/windows_100_kmax_3322/IM_BA --sliced me`

`--sliced me` is optional, but provides likelihoods and parameter estimates conditional on each m_e values (or some other parameter).

Is it worth adding a description of the `query` module to the README to help users with this step?

I also noticed that @ala98412 uses `-w 500` when making windows. This is the default, but I don't think it is useful as 500 blocks contains very little information. I would suggest increasing the default to something like 50_000, or removing the default value altogether.

Cheers,

Alex

**Comment by GertjanBisschop** [comment]
Thanks @A-J-F-Mackintosh!
